<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="DocAppToday.aspx.cs" Inherits="WebApplication1.PendingAppointment" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <style>
        h1   {color:#32a885; 
              font-family: "Segoe UI", Arial, sans-serif;
              text-align: center;
        }

    </style>

     <h1><strong>Welcome! You have the following Appointments today</strong></h1>
    <br /><br />

<div>

     <asp:GridView ID="DocAppToday" class="GridView-d"
        runat="server"
         AutoGenerateDeleteButton="True"
           EnableViewState="False"
          OnRowDeleting="removeApp" BackColor="White" BorderColor="#DEDFDE"
         BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Vertical" HorizontalAlign="Center"
         >
         <HeaderStyle BackColor="#FF7F50" Font-Bold="True" ForeColor="White" />
        <RowStyle BackColor="#F7F7DE" />
        <AlternatingRowStyle BackColor="White" />
        <FooterStyle BackColor="#CCCC99" />
        <SelectedRowStyle BackColor="#CE5D5A" Font-Bold="True" ForeColor="White" />   
        </asp:GridView>
 </div>
    <div class="row">
                      <div class="border-right">
                          
                                      <a href="Doctor.aspx" type="button" class="btn btn-primary btn-lg" >Back to Home</a>

                      </div>
                    </div>
    <br /><br/>
</asp:Content>
